#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""tools/build_catalog_data.py — 从 data/catalog.json 生成 lib/catalog_data.js。

把 catalog.json 转成 JS 格式（episodes 转成 {数字: token} 对象，id 转成 vod-${vod_id}），
内嵌到 lib/catalog_data.js 作为 Turso 不可用时的兜底片库。

用法:
    python3 tools/build_catalog_data.py
"""
import json
import os
import re
import sys
from datetime import datetime

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(BASE, "data", "catalog.json")
DST = os.path.join(BASE, "lib", "catalog_data.js")

if not os.path.exists(SRC):
    print(f"ERROR: {SRC} not found. Run import_detail.py first.", file=sys.stderr)
    sys.exit(1)

with open(SRC, encoding="utf-8") as f:
    data = json.load(f)

vods = {}
for raw_id, vod in (data.get("vods") or {}).items():
    movie = {
        "id": f"vod-{raw_id}",
        "vod_id": raw_id,
        "name": vod.get("vod_name", ""),
        "vod_pic": vod.get("vod_pic", ""),
        "vod_remarks": vod.get("vod_remarks", ""),
        "vod_class": vod.get("vod_class", ""),
        "vod_content": vod.get("vod_content", ""),
        "vod_info": {
            "vod_name": vod.get("vod_name", ""),
            "vod_pic": vod.get("vod_pic", ""),
            "vod_remarks": vod.get("vod_remarks", ""),
            "vod_class": vod.get("vod_class", ""),
            "vod_content": vod.get("vod_content", ""),
        },
        "sources": {},
        "imported_at": vod.get("imported_at", ""),
    }
    for code, src in (vod.get("sources") or {}).items():
        episodes = {}
        for ep in src.get("episodes", []):
            if isinstance(ep, list) and len(ep) == 2:
                name, token = ep
                m = re.search(r"(\d+)", str(name))
                key = str(int(m.group(1))) if m else "0"
                episodes[key] = token
            elif isinstance(ep, dict):
                episodes.update(ep)
        movie["sources"][code] = {
            "name": src.get("name", code),
            "parse_api": src.get("parse_api", ""),
            "headers": src.get("headers", ""),
            "core_params": src.get("core_params", []),
            "episodes": episodes,
        }
    vods[raw_id] = movie

now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
total_eps = sum(
    sum(len(s["episodes"]) for s in v["sources"].values())
    for v in vods.values()
)

js_content = f"""// lib/catalog_data.js — AUTO-GENERATED by tools/build_catalog_data.py
// DO NOT EDIT BY HAND — run `python3 tools/build_catalog_data.py` to regenerate.
// Source: data/catalog.json  Generated: {now}
// Embedded fallback catalog: used when Turso is unavailable.
// Contains {len(vods)} vods, {total_eps} episodes total.

export const EMBEDDED_CATALOG = {{
  vods: {json.dumps(vods, ensure_ascii=False)},
}};
"""

with open(DST, "w", encoding="utf-8") as f:
    f.write(js_content)

size = os.path.getsize(DST)
print(f"Generated {DST}: {len(vods)} vods, {total_eps} episodes, {size} bytes")
